name: Testing

on:
  push:
    branches:
      - main

jobs:
  unit:
    if: false
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: pnpm install
      - name: Run unit tests
        run: pnpm test:unit
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: coverage/

  integration:
    runs-on: self-hosted
    services:
      webdav:
        image: bytemark/webdav
        ports:
          - 60080:80
        env:
          AUTH_TYPE: Basic
          USERNAME: alice
          PASSWORD: secret1234
        options: --name webdav
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Copy test data to container
        run: docker cp ./tests/integration/test-data webdav:/var/lib/dav/dav
      - name: Debug step
        run: docker exec webdav ls /var/lib/dav/dav
      - name: Install dependencies
        run: pnpm install
      - name: Run integration tests
        run: pnpm test:integration
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: coverage/

  e2e:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

  load:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
